{% set name = "optics_functions" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optics_functions-{{ version }}.tar.gz
  sha256: 40c8f5dac12a45f5b158a276e43bb402d817e58db1f24203181f126fc0fb9f87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19.0
    - pandas >=1.0
    - python >=3.6
    - tfs-pandas >=2.0

test:
  imports:
    - optics_functions
    - optics_functions.coupling
    - optics_functions.rdt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/optics_functions
  summary: Calculate particle accelerator optics parameters from TWISS outputs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Python package to calculate various particle accelerator optics parameters from MAD-X TWISS outputs.
  doc_url: https://pylhc.github.io/optics_functions/

extra:
  recipe-maintainers:
    - fsoubelet
